[package]
name = "directory_walking"
version = "0.1.0"
authors = ["Nick <speedyleion@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.6.0"
ntapi = "0.3.6"
memoffset = "0.6.3"

[dependencies.winapi]
version = "0.3.9"
features = ["fileapi", "winbase"]